[finance]

   path = /srv/shared/finance

   valid users = @finance

   read only = no

   browsable = yes



[dev]

   path = /srv/shared/dev

   valid users = @dev

   read only = no

   browsable = yes



[hr]

   path = /srv/shared/hr

   valid users = @hr

   read only = no

   browsable = yes